# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(394, 307)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.record_screen_btn = QtWidgets.QPushButton(self.centralwidget)
        self.record_screen_btn.setGeometry(QtCore.QRect(140, 150, 111, 41))
        self.record_screen_btn.setObjectName("record_screen_btn")
        self.path = QtWidgets.QLineEdit(self.centralwidget)
        self.path.setGeometry(QtCore.QRect(60, 90, 231, 31))
        self.path.setStyleSheet("background-color:grey;")
        self.path.setReadOnly(True)
        self.path.setObjectName("path")
        self.choose_path_btn = QtWidgets.QPushButton(self.centralwidget)
        self.choose_path_btn.setGeometry(QtCore.QRect(300, 90, 41, 31))
        self.choose_path_btn.setObjectName("choose_path_btn")
        self.stop_record_screen_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_record_screen_btn.setGeometry(QtCore.QRect(140, 150, 111, 41))
        self.stop_record_screen_btn.setObjectName("stop_record_screen_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 210, 191, 17))
        self.label.setObjectName("label")
        self.link = QtWidgets.QLabel(self.centralwidget)
        self.link.setGeometry(QtCore.QRect(160, 230, 291, 21))
        self.link.setOpenExternalLinks(True)
        self.link.setObjectName("link")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 20, 101, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/record.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 30, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 394, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Screen Recorder"))
        self.record_screen_btn.setText(_translate("MainWindow", "Record Screen"))
        self.choose_path_btn.setText(_translate("MainWindow", "..."))
        self.stop_record_screen_btn.setText(_translate("MainWindow", "Stop Rec"))
        self.label.setText(_translate("MainWindow", "Developed by Pedro Neto"))
        self.link.setText(_translate("MainWindow", "<a style=\"text-align:center;\" href=\"https://github.com/pedropamn/ScreenRecorder\">Github</a>"))
        self.label_3.setText(_translate("MainWindow", "Screen Recorder"))
#import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
